site_name: CIS&T OpenStack Guide
pages:
    - Home: "index.md"
    - User Guide:
        - "Getting Started" : "user_guide/getting_started.md"
        - "Exploring the Dashboard" : "user_guide/explore_dashboard.md"
        - "Setting up Your Project" : "user_guide/setup.md"
        - "Image Information" : "user_guide/image_info.md"
theme: readthedocs
