site_name: CIS&T OpenStack Guide
pages:
    - Home: "index.md"
    - User Guide:
        - "Getting Started" : "user_guide/getting_started.md"
        - "Exploring the Dashboard" : "user_guide/explore_dashboard.md"
        - "Setting up Your Project" : "user_guide/setup.md"
        - "Image Information" : "user_guide/image_info.md"
        - "Flavor References" : "user_guide/flavors.md"
        - "Launching a Windows Instance" : "user_guide/launching_windows.md"
        - "Docker Guide" : "user_guide/
    - Admin Guide:
        - "Getting Started" : "admin_guide/getting_started.md"
        - Adding a Compute Node:
          - "Imaging a Compute Node": "admin_guide/adding_compute_nodes/imaging.md" 
        - Packstack Liberty: "admin_guide/packstack/packstack_index.md"
        - Troubleshooting:
          - "Calling 'http://169.254.169.254...'" : "admin_guide/troubleshooting/calling.md"
          - "Packstack fail: Django" : "admin_guide/troubleshooting/packstacks_django.md"
          - "HTTPD fails" : "admin_guide/troubleshooting/http_fails.md"
        - Image Creation:
          - "CentOS 7" : "admin_guide/image_creation/centos7_image_creation.md"
          - "Ubuntu" : "admin_guide/image_creation/ubuntu_image_creation.md"
        - Runbooks:
          - "Data Bag Users" : "admin_guide/runbooks/add_user_data_bag_items.md"
theme: readthedocs
