--- # Compute node install playbook
- hosts: leftovers
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Download git
    yum:
      name: git
      state: latest
  - name: Clone CIST-Openstack
    git:
      repo: 'https://github.com/cist-openstack/openstack.git'
      dest: /root/openstack
      clone: yes
      update: yes
      force: yes
  - name: Execute compute_prep.sh
    script: /root/openstack/compute_prep.sh
#  - name: Reboot
#    command: shutdown -r +1
