--- # Compute node install playbook
- hosts: compute
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Download git
    yum:
      name: git
      state: latest
  - name: Clone CIST-Openstack
    git:
      repo: 'https://github.com/cist-openstack/openstack.git'
      dest: /root/openstack
      clone: yes
      update: yes
      force: yes
  - name: Overwrite /etc/nova/nova.conf
    copy:
      src: /root/openstack/compute_bootstrap/nova.conf
      dest: /etc/nova/nova.conf
      force: yes
  - name: Restart nova
    service:
      name: openstack-nova-compute
      state: restarted
