--- # Compute node install playbook
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Clone CIST-Openstack
    git:
      repo: 'https://github.com/cist-openstack/openstack.git'
      dest: /root/openstack
      clone: yes
      update: yes
      force: yes
  - name: Install epel
    yum:
      name: epel-release
      state: latest
  - name: Download telegraf
    get_url:
      url: https://dl.influxdata.com/telegraf/releases/telegraf-1.2.1.x86_64.rpm
      dest: /root/telegraf-1.2.1.x86_64.rpm    
  - name: Install telegraf
    yum:
      name: /root/telegraf-1.2.1.x86_64.rpm
  - name: Overwrite telegraf config
    copy:
      src: /root/openstack/telegraf/hangar-snapstack-lab/telegraf.conf
      dest: /etc/telegraf/telegraf.conf
      force: yes
  - name: Start/Enable Telegraf
    service:
      name: telegraf
      state: restarted 
